qQOLcfG7: Add missing dependency on Java11
When running on Java 11 the following dependency is needed:
```
javax.activation:javax.activation-api:1.2.0
```

Otherwise when you start the VSP there are lots of warning messages
related to:
```
java.lang.NoClassDefFoundError: javax/activation/DataSource
```